name: "Test"

on:
  push:
    branches:
      - main

jobs:
  test:
    # only run if commit message contains '!test'
    if: contains(github.event.head_commit.message, '!test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read commit and apply to kubernetes
        uses: ./
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          set-cf-dns: false
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-email: ${{ secrets.GHCR_EMAIL }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
          gh-token: ${{ secrets.GH_TOKEN }}
